# Generated by Django 5.0.3 on 2024-04-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_cliente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
